/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as ierc20Sol from "./IERC20 .sol";
export type { ierc20Sol };
import type * as tbillVaultSol from "./TbillVault.sol";
export type { tbillVaultSol };
import type * as tBillTokenSol from "./tBillToken.sol";
export type { tBillTokenSol };
