/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenSol from "./ERC20Token.sol";
export type { erc20TokenSol };
import type * as tBillSol from "./tBill.sol";
export type { tBillSol };
import type * as tBillTokenSol from "./tBillToken.sol";
export type { tBillTokenSol };
export type { IERC20 } from "./IERC20";
