/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20TokenSol from "./ERC20Token.sol";
export * as tBillSol from "./tBill.sol";
export * as tBillTokenSol from "./tBillToken.sol";
export { IERC20__factory } from "./IERC20__factory";
